[build]
  base = "ui"
  command = "npm install --legacy-peer-deps && npm run build -- --configuration=production"
  publish = "dist/neco/browser"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
